version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 515966515062.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t demo2 .
      - docker tag demo2:latest 515966515062.dkr.ecr.ap-south-1.amazonaws.com/demo2:latest
  post_build:
    commands:
      - docker push 515966515062.dkr.ecr.ap-south-1.amazonaws.com/demo2:latest
      - echo Writing image definitions file...
      - printf '[{"name":"demo2","imageUri":"%s"}]' 515966515062.dkr.ecr.ap-south-1.amazonaws.com/demo2:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json